#!/usr/bin/env bash
set -Eeuo pipefail
umask 027

readonly SERVER_DIR=/mnt/server
readonly IMAGE_ROOT=/opt/nextcloud-egg
readonly RUNTIME_TEMPLATE_ROOT="${IMAGE_ROOT}/runtime"
readonly EXPECTED_IMAGE_API_VERSION=1
readonly INSTALL_TMP="${SERVER_DIR}/.nextcloud-egg-install"

# Pterodactyl's installer container can expose a small /tmp. Keep the large
# release archive and extracted core on the server volume instead.
mkdir -p "$SERVER_DIR"
rm -rf -- "$INSTALL_TMP"
mkdir -p "$INSTALL_TMP"

cleanup() {
	rm -rf -- "$INSTALL_TMP"
}
trap cleanup EXIT

log() {
	printf '[Installer] %s\n' "$*"
}

fatal() {
	printf '[Installer] ERROR: %s\n' "$*" >&2
	exit 1
}

is_enabled() {
	case "${1:-}" in
		1|true|TRUE|yes|YES|on|ON) return 0 ;;
		*) return 1 ;;
	esac
}

verify_image() {
	local actual_version=""
	[[ -r "${IMAGE_ROOT}/IMAGE_API_VERSION" ]] \
		&& actual_version="$(tr -d '\r\n' < "${IMAGE_ROOT}/IMAGE_API_VERSION")"
	[[ "$actual_version" == "$EXPECTED_IMAGE_API_VERSION" ]] \
		|| fatal "Incompatible Nextcloud image API '${actual_version:-missing}'; expected ${EXPECTED_IMAGE_API_VERSION}."

	local command_name
	for command_name in curl mariadb-install-db openssl rsync sha256sum unzip; do
		command -v "$command_name" >/dev/null 2>&1 \
			|| fatal "Required image command is missing: ${command_name}."
	done
	[[ -d "$RUNTIME_TEMPLATE_ROOT" ]] || fatal "Runtime templates are missing from the image."
}

install_runtime_configuration() {
	local directory
	log "Installing versioned Nginx, PHP, MariaDB, and Redis configuration templates."
	for directory in nginx php; do
		mkdir -p "${SERVER_DIR}/${directory}"
		rsync -a "${RUNTIME_TEMPLATE_ROOT}/${directory}/" "${SERVER_DIR}/${directory}/"
	done
	# Generated by the former inline installer; system extensions now come from the image.
	rm -f -- "${SERVER_DIR}/php/conf.d/10-local-extensions.ini"

	mkdir -p "${SERVER_DIR}/services/mariadb" "${SERVER_DIR}/services/redis"
	install -m 0644 "${RUNTIME_TEMPLATE_ROOT}/services/mariadb/my.cnf" \
		"${SERVER_DIR}/services/mariadb/my.cnf"
	install -m 0644 "${RUNTIME_TEMPLATE_ROOT}/services/redis/redis.conf" \
		"${SERVER_DIR}/services/redis/redis.conf"
}

initialize_mariadb() {
	local data_directory="${SERVER_DIR}/services/mariadb/data"
	if [[ -d "${data_directory}/mysql" ]]; then
		log "Keeping the existing embedded MariaDB data directory."
		return 0
	fi

	log "Initializing the embedded MariaDB data directory."
	mkdir -p "$data_directory"
	mariadb-install-db \
		--datadir="$data_directory" \
		--auth-root-authentication-method=normal \
		--skip-test-db \
		--user=root >/dev/null
}

ensure_secrets() {
	mkdir -p "${SERVER_DIR}/.secrets"
	chmod 700 "${SERVER_DIR}/.secrets"
	if [[ ! -s "${SERVER_DIR}/.secrets/database_password" ]]; then
		openssl rand -hex 32 > "${SERVER_DIR}/.secrets/database_password"
	fi
	if [[ -n "${WHITEBOARD_JWT_SECRET:-}" ]]; then
		printf '%s' "$WHITEBOARD_JWT_SECRET" > "${SERVER_DIR}/.secrets/whiteboard_jwt_secret"
	elif [[ ! -s "${SERVER_DIR}/.secrets/whiteboard_jwt_secret" ]]; then
		openssl rand -hex 32 > "${SERVER_DIR}/.secrets/whiteboard_jwt_secret"
	fi
	chmod 600 "${SERVER_DIR}/.secrets/database_password" "${SERVER_DIR}/.secrets/whiteboard_jwt_secret"
}

download_nextcloud() {
	local version="$1"
	local archive="$INSTALL_TMP/nextcloud.zip"
	local checksum_file="$INSTALL_TMP/nextcloud.zip.sha256"
	local base_url=https://download.nextcloud.com/server/releases
	local archive_name
	local checksum

	if [[ "$version" == latest ]]; then
		archive_name=latest.zip
	else
		[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fatal "Invalid NEXTCLOUD_VERSION: ${version}"
		archive_name="nextcloud-${version}.zip"
	fi

	log "Downloading official Nextcloud release ${version}."
	curl -fL --retry 5 --retry-delay 2 -o "$archive" "${base_url}/${archive_name}"
	curl -fL --retry 5 --retry-delay 2 -o "$checksum_file" "${base_url}/${archive_name}.sha256"
	checksum="$(awk 'NR == 1 { print $1 }' "$checksum_file")"
	[[ "$checksum" =~ ^[a-fA-F0-9]{64}$ ]] || fatal "Invalid Nextcloud SHA-256 file."
	printf '%s  %s\n' "$checksum" "$archive" | sha256sum --check --status \
		|| fatal "Nextcloud archive checksum verification failed."

	rm -rf -- "$INSTALL_TMP/nextcloud"
	unzip -q "$archive" -d "$INSTALL_TMP"
	rm -f -- "$archive" "$checksum_file"
}

installed_nextcloud_version() {
	local version_file="${SERVER_DIR}/www/version.php"
	[[ -f "$version_file" ]] || return 1
	sed -n "s/.*OC_VersionString[[:space:]]*=[[:space:]]*'\([^']*\)'.*/\1/p" "$version_file" | head -n 1
}

migrate_legacy_apps() {
	local pristine_root="$1"
	local web_root="$2"
	local installed_app
	local app_id
	local destination

	[[ -d "${web_root}/apps" ]] || return 0
	mkdir -p "${web_root}/custom_apps"
	for installed_app in "${web_root}/apps"/*; do
		[[ -d "$installed_app" ]] || continue
		app_id="$(basename "$installed_app")"
		[[ -d "${pristine_root}/apps/${app_id}" ]] && continue
		destination="${web_root}/custom_apps/${app_id}"
		log "Preserving non-shipped app '${app_id}' in custom_apps before core repair."
		mkdir -p "$destination"
		rsync -a --delete "${installed_app}/" "${destination}/"
	done
}

install_or_repair_nextcloud() {
	local web_root="${SERVER_DIR}/www"
	local existing_version=""
	local requested_version="${NEXTCLOUD_VERSION:-latest}"

	mkdir -p "$web_root" "${SERVER_DIR}/data" "${SERVER_DIR}/backups"
	existing_version="$(installed_nextcloud_version || true)"

	if [[ -n "$existing_version" ]]; then
		if ! is_enabled "${REPAIR_EXISTING_CORE:-true}"; then
			log "Keeping existing Nextcloud ${existing_version} core without repair."
			return 0
		fi
		download_nextcloud "$existing_version"
		migrate_legacy_apps "${INSTALL_TMP}/nextcloud" "$web_root"
		log "Restoring official core files for Nextcloud ${existing_version}; config and user data are preserved."
		rsync -a \
			--delete \
			--exclude=/config/ \
			--exclude=/data/ \
			--exclude=/custom_apps/ \
			--exclude=/themes/ \
			"${INSTALL_TMP}/nextcloud/" "$web_root/"
		return 0
	fi

	if [[ -n "$(find "$web_root" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
		fatal "www is not empty and does not contain a recognizable Nextcloud installation. Move those files before reinstalling."
	fi

	download_nextcloud "$requested_version"
	log "Installing pristine Nextcloud core files."
	rmdir "$web_root"
	mv -- "${INSTALL_TMP}/nextcloud" "$web_root"
}

mkdir -p "$SERVER_DIR" "${SERVER_DIR}/logs" "${SERVER_DIR}/tmp" "${SERVER_DIR}/.state"

verify_image
install_runtime_configuration
ensure_secrets
initialize_mariadb
install_or_repair_nextcloud

log "Installation completed successfully."
