bind 127.0.0.1
protected-mode yes
port 6379
daemonize no
supervised no
pidfile /home/container/tmp/redis.pid
loglevel notice
logfile /home/container/logs/redis.log
databases 2
save ""
appendonly no
dir /home/container/services/redis
maxmemory 256mb
maxmemory-policy noeviction
timeout 0
tcp-keepalive 300
